### PR TITLE
Website Update

### PR DESCRIPTION
**Pull request by rupeshkumar22**
This PR aims to resolve the existing issues on the website repository. Moreover, we are planning to update tutorials, pages, and images from older PDE versions on the website as [discussed here](https://github.com/codeanticode/processing-android-website/issues/24).

Right now I'm focussing on current issues on the website. Moving forward in discussions with @codeanticode and @ranaaditya we will see what can be prioritized for the website improvements. Discussions from anyone regarding website improvements are always welcome.

Regards,
Rupesh Kumar

### CODE REVIEW

**Review by ranaaditya — APPROVED** [review]

**Comment by ranaaditya** [comment]
Hi @codeanticode , can you please review this PR and merge it if It looks good to you.

Thanks,
Aditya Rana

**Comment by rupeshkumar22** [comment]
Hi @ranaaditya thanks for reviewing the current changes, Shall I add more changes and then change this from draft PR to Ready to merge PR? I'm planning to replace the old tutorial screenshots with the new processing 4 screenshots. I would take your suggestions as a priority.
Thanks!

**Review by ranaaditya — APPROVED** [review]

**Comment by ranaaditya** [comment]
hi @codeanticode , changes LGTM 👍 , you can review it and merge.

thanks,
Rana :)

**Comment by SableRaf** [comment]
Thanks for you contribution @rupeshkumar22 ✨ Sorry it took so long to merge

**Pull request merged**
